name: serial_data_acquisition
version: 2.0.0+2
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  expansion_tile_card: ^3.0.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.0.0
  flutter_libserialport: ^0.3.0
  form_builder_validators: ^9.0.0
  get: ^4.6.5
  path_provider: ^2.0.15
  rxdart: ^0.27.5
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.11
  window_manager: ^0.3.4

dev_dependencies:
  dart_code_metrics: ^5.7.5
  flutter_launcher_icons: ^0.13.1
  lint: ^2.1.2


flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  windows:
    generate: true
    image_path: "assets/images/tachlog_logo.png"
  linux:
    generate: true
    image_path: "assets/images/tachlog_logo.png"

