name: serial-data-acquisition
version: 0.0.1
summary: Serial Data Acquisition
description: Serial Data Acquisition
confinement: strict
base: core18
grade: stable

apps:
  serial-data-acquisition:
    command: serial_data_acquisition
    extensions: [flutter-master]
    plugs:
      - desktop
      - home
      - personal-files
      - removable-media
      - serial-port
      - raw-input
      - raw-usb

parts:
  serial-data-acquisition:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
